package com.mnp.TwitterTrends.bolt;

import java.util.Map;

import org.codehaus.jackson.map.ObjectMapper;
import org.zeromq.ZMQ;

import com.mnp.herontweets.tools.DataGeneratorTrends;
import com.mnp.herontweets.tools.Rankings;

import backtype.storm.task.TopologyContext;
import backtype.storm.topology.BasicOutputCollector;
import backtype.storm.topology.OutputFieldsDeclarer;
import backtype.storm.tuple.Tuple;

/**
 * This bolt merges incoming {@link Rankings}.
 * 
 * It can be used to merge intermediate rankings generated by
 * {@link IntermediateRankingsBolt} into a final, consolidated ranking. To do
 * so, configure this bolt with a globalGrouping on
 * {@link IntermediateRankingsBolt}.
 * 
 */
public final class TotalRankingsBolt extends AbstractRankerBolt {

	private static final long serialVersionUID = -8447525895532302198L;
	private ZMQ.Socket sender;
	private ZMQ.Context context;
	private DataGeneratorTrends s = new DataGeneratorTrends();

	public TotalRankingsBolt() {
		super();
	}

	public TotalRankingsBolt(int topN) {
		super(topN);
	}

	public TotalRankingsBolt(int topN, int emitFrequencyInSeconds) {
		super(topN, emitFrequencyInSeconds);
	}

	@Override
	public void prepare(Map conf, TopologyContext ctx) {
		
	}

	@Override
	void updateRankingsWithTuple(Tuple tuple) {
		Rankings rankingsToBeMerged = (Rankings) tuple.getValue(0);
		super.getRankings().updateWith(rankingsToBeMerged);
	}

	@Override
	public void declareOutputFields(OutputFieldsDeclarer ofd) {
	}

	@Override
	public void emitRankings(BasicOutputCollector collector) {
		ObjectMapper objectMapper = new ObjectMapper();
		String json = "";
		try {
			json = objectMapper.writeValueAsString(getRankings());
			System.out.println("!!!!!!!!!!!!!!"+json);
		} catch (Exception e) {
			e.printStackTrace();
		}
	//	sender.send(json.getBytes(), 0);
		s.dataGenerator(json);
	
	}
}
